gazebo_ros_control:
  pid_gains:
    # these gains are used by the gazebo_ros_control plugin
    gimbal_r_joint:
      p: 100.0
      i: 0.01
      d: 0.0
    gimbal_p_joint:
      p: 100.0
      i: 0.01
      d: 0.0
    gimbal_y_joint:
      p: 100.0
      i: 0.01
      d: 0.0
    front_axle_joint:
      p: 100.0
      i: 0.01
      d: 0.0
    back_axle_joint:
      p: 100.0
      i: 0.01
      d: 0.0
