(cl:defpackage sensor_fusion_comm-srv
  (:use )
  (:export
   "INITHEIGHT"
   "<INITHEIGHT-REQUEST>"
   "INITHEIGHT-REQUEST"
   "<INITHEIGHT-RESPONSE>"
   "INITHEIGHT-RESPONSE"
   "INITSCALE"
   "<INITSCALE-REQUEST>"
   "INITSCALE-REQUEST"
   "<INITSCALE-RESPONSE>"
   "INITSCALE-RESPONSE"
  ))

