// Generated by gencpp from file sensor_fusion_comm/InitHeight.msg
// DO NOT EDIT!


#ifndef SENSOR_FUSION_COMM_MESSAGE_INITHEIGHT_H
#define SENSOR_FUSION_COMM_MESSAGE_INITHEIGHT_H

#include <ros/service_traits.h>


#include <sensor_fusion_comm/InitHeightRequest.h>
#include <sensor_fusion_comm/InitHeightResponse.h>


namespace sensor_fusion_comm
{

struct InitHeight
{

typedef InitHeightRequest Request;
typedef InitHeightResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct InitHeight
} // namespace sensor_fusion_comm


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sensor_fusion_comm::InitHeight > {
  static const char* value()
  {
    return "6b19ce060384743d60708a804f1c749f";
  }

  static const char* value(const ::sensor_fusion_comm::InitHeight&) { return value(); }
};

template<>
struct DataType< ::sensor_fusion_comm::InitHeight > {
  static const char* value()
  {
    return "sensor_fusion_comm/InitHeight";
  }

  static const char* value(const ::sensor_fusion_comm::InitHeight&) { return value(); }
};


// service_traits::MD5Sum< ::sensor_fusion_comm::InitHeightRequest> should match 
// service_traits::MD5Sum< ::sensor_fusion_comm::InitHeight > 
template<>
struct MD5Sum< ::sensor_fusion_comm::InitHeightRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sensor_fusion_comm::InitHeight >::value();
  }
  static const char* value(const ::sensor_fusion_comm::InitHeightRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sensor_fusion_comm::InitHeightRequest> should match 
// service_traits::DataType< ::sensor_fusion_comm::InitHeight > 
template<>
struct DataType< ::sensor_fusion_comm::InitHeightRequest>
{
  static const char* value()
  {
    return DataType< ::sensor_fusion_comm::InitHeight >::value();
  }
  static const char* value(const ::sensor_fusion_comm::InitHeightRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sensor_fusion_comm::InitHeightResponse> should match 
// service_traits::MD5Sum< ::sensor_fusion_comm::InitHeight > 
template<>
struct MD5Sum< ::sensor_fusion_comm::InitHeightResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sensor_fusion_comm::InitHeight >::value();
  }
  static const char* value(const ::sensor_fusion_comm::InitHeightResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sensor_fusion_comm::InitHeightResponse> should match 
// service_traits::DataType< ::sensor_fusion_comm::InitHeight > 
template<>
struct DataType< ::sensor_fusion_comm::InitHeightResponse>
{
  static const char* value()
  {
    return DataType< ::sensor_fusion_comm::InitHeight >::value();
  }
  static const char* value(const ::sensor_fusion_comm::InitHeightResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SENSOR_FUSION_COMM_MESSAGE_INITHEIGHT_H
