// Generated by gencpp from file sensor_fusion_comm/InitScale.msg
// DO NOT EDIT!


#ifndef SENSOR_FUSION_COMM_MESSAGE_INITSCALE_H
#define SENSOR_FUSION_COMM_MESSAGE_INITSCALE_H

#include <ros/service_traits.h>


#include <sensor_fusion_comm/InitScaleRequest.h>
#include <sensor_fusion_comm/InitScaleResponse.h>


namespace sensor_fusion_comm
{

struct InitScale
{

typedef InitScaleRequest Request;
typedef InitScaleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct InitScale
} // namespace sensor_fusion_comm


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sensor_fusion_comm::InitScale > {
  static const char* value()
  {
    return "f8ea41d14f4e256b53793fe5b7588158";
  }

  static const char* value(const ::sensor_fusion_comm::InitScale&) { return value(); }
};

template<>
struct DataType< ::sensor_fusion_comm::InitScale > {
  static const char* value()
  {
    return "sensor_fusion_comm/InitScale";
  }

  static const char* value(const ::sensor_fusion_comm::InitScale&) { return value(); }
};


// service_traits::MD5Sum< ::sensor_fusion_comm::InitScaleRequest> should match 
// service_traits::MD5Sum< ::sensor_fusion_comm::InitScale > 
template<>
struct MD5Sum< ::sensor_fusion_comm::InitScaleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sensor_fusion_comm::InitScale >::value();
  }
  static const char* value(const ::sensor_fusion_comm::InitScaleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sensor_fusion_comm::InitScaleRequest> should match 
// service_traits::DataType< ::sensor_fusion_comm::InitScale > 
template<>
struct DataType< ::sensor_fusion_comm::InitScaleRequest>
{
  static const char* value()
  {
    return DataType< ::sensor_fusion_comm::InitScale >::value();
  }
  static const char* value(const ::sensor_fusion_comm::InitScaleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sensor_fusion_comm::InitScaleResponse> should match 
// service_traits::MD5Sum< ::sensor_fusion_comm::InitScale > 
template<>
struct MD5Sum< ::sensor_fusion_comm::InitScaleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sensor_fusion_comm::InitScale >::value();
  }
  static const char* value(const ::sensor_fusion_comm::InitScaleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sensor_fusion_comm::InitScaleResponse> should match 
// service_traits::DataType< ::sensor_fusion_comm::InitScale > 
template<>
struct DataType< ::sensor_fusion_comm::InitScaleResponse>
{
  static const char* value()
  {
    return DataType< ::sensor_fusion_comm::InitScale >::value();
  }
  static const char* value(const ::sensor_fusion_comm::InitScaleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SENSOR_FUSION_COMM_MESSAGE_INITSCALE_H
