//#line 2 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the msf_updates package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __msf_updates__POSITIONPOSESENSORCONFIG_H__
#define __msf_updates__POSITIONPOSESENSORCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace msf_updates
{
  class PositionPoseSensorConfigStatics;

  class PositionPoseSensorConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }

      virtual void clamp(PositionPoseSensorConfig &config, const PositionPoseSensorConfig &max, const PositionPoseSensorConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const PositionPoseSensorConfig &config1, const PositionPoseSensorConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, PositionPoseSensorConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const PositionPoseSensorConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, PositionPoseSensorConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const PositionPoseSensorConfig &config) const = 0;
      virtual void getValue(const PositionPoseSensorConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T PositionPoseSensorConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T (PositionPoseSensorConfig::* field);

      virtual void clamp(PositionPoseSensorConfig &config, const PositionPoseSensorConfig &max, const PositionPoseSensorConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const PositionPoseSensorConfig &config1, const PositionPoseSensorConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, PositionPoseSensorConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const PositionPoseSensorConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, PositionPoseSensorConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const PositionPoseSensorConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const PositionPoseSensorConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, PositionPoseSensorConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, PositionPoseSensorConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<PositionPoseSensorConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(PositionPoseSensorConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("core_init_filter"==(*_i)->name){core_init_filter = boost::any_cast<bool>(val);}
        if("core_set_height"==(*_i)->name){core_set_height = boost::any_cast<bool>(val);}
        if("core_height"==(*_i)->name){core_height = boost::any_cast<double>(val);}
        if("pose_initial_scale"==(*_i)->name){pose_initial_scale = boost::any_cast<double>(val);}
        if("pose_fixed_scale"==(*_i)->name){pose_fixed_scale = boost::any_cast<bool>(val);}
        if("pose_fixed_p_ic"==(*_i)->name){pose_fixed_p_ic = boost::any_cast<bool>(val);}
        if("pose_fixed_q_ic"==(*_i)->name){pose_fixed_q_ic = boost::any_cast<bool>(val);}
        if("pose_fixed_p_wv"==(*_i)->name){pose_fixed_p_wv = boost::any_cast<bool>(val);}
        if("pose_fixed_q_wv"==(*_i)->name){pose_fixed_q_wv = boost::any_cast<bool>(val);}
        if("pose_noise_scale"==(*_i)->name){pose_noise_scale = boost::any_cast<double>(val);}
        if("pose_noise_p_wv"==(*_i)->name){pose_noise_p_wv = boost::any_cast<double>(val);}
        if("pose_noise_q_wv"==(*_i)->name){pose_noise_q_wv = boost::any_cast<double>(val);}
        if("pose_noise_p_ic"==(*_i)->name){pose_noise_p_ic = boost::any_cast<double>(val);}
        if("pose_noise_q_ic"==(*_i)->name){pose_noise_q_ic = boost::any_cast<double>(val);}
        if("pose_noise_meas_p"==(*_i)->name){pose_noise_meas_p = boost::any_cast<double>(val);}
        if("pose_noise_meas_q"==(*_i)->name){pose_noise_meas_q = boost::any_cast<double>(val);}
        if("pose_delay"==(*_i)->name){pose_delay = boost::any_cast<double>(val);}
        if("position_noise_meas"==(*_i)->name){position_noise_meas = boost::any_cast<double>(val);}
        if("position_yaw_init"==(*_i)->name){position_yaw_init = boost::any_cast<double>(val);}
        if("position_delay"==(*_i)->name){position_delay = boost::any_cast<double>(val);}
        if("position_noise_p_ip"==(*_i)->name){position_noise_p_ip = boost::any_cast<double>(val);}
        if("position_fixed_p_ip"==(*_i)->name){position_fixed_p_ip = boost::any_cast<bool>(val);}
      }
    }

    bool core_init_filter;
bool core_set_height;
double core_height;
double pose_initial_scale;
bool pose_fixed_scale;
bool pose_fixed_p_ic;
bool pose_fixed_q_ic;
bool pose_fixed_p_wv;
bool pose_fixed_q_wv;
double pose_noise_scale;
double pose_noise_p_wv;
double pose_noise_q_wv;
double pose_noise_p_ic;
double pose_noise_q_ic;
double pose_noise_meas_p;
double pose_noise_meas_q;
double pose_delay;
double position_noise_meas;
double position_yaw_init;
double position_delay;
double position_noise_p_ip;
bool position_fixed_p_ip;

    bool state;
    std::string name;

    
}groups;



//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool core_init_filter;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool core_set_height;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double core_height;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double pose_initial_scale;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool pose_fixed_scale;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool pose_fixed_p_ic;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool pose_fixed_q_ic;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool pose_fixed_p_wv;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool pose_fixed_q_wv;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double pose_noise_scale;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double pose_noise_p_wv;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double pose_noise_q_wv;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double pose_noise_p_ic;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double pose_noise_q_ic;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double pose_noise_meas_p;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double pose_noise_meas_q;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double pose_delay;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double position_noise_meas;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double position_yaw_init;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double position_delay;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double position_noise_p_ip;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool position_fixed_p_ip;
//#line 228 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("PositionPoseSensorConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const PositionPoseSensorConfig &__max__ = __getMax__();
      const PositionPoseSensorConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const PositionPoseSensorConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const PositionPoseSensorConfig &__getDefault__();
    static const PositionPoseSensorConfig &__getMax__();
    static const PositionPoseSensorConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const PositionPoseSensorConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void PositionPoseSensorConfig::ParamDescription<std::string>::clamp(PositionPoseSensorConfig &config, const PositionPoseSensorConfig &max, const PositionPoseSensorConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class PositionPoseSensorConfigStatics
  {
    friend class PositionPoseSensorConfig;

    PositionPoseSensorConfigStatics()
    {
PositionPoseSensorConfig::GroupDescription<PositionPoseSensorConfig::DEFAULT, PositionPoseSensorConfig> Default("Default", "", 0, 0, true, &PositionPoseSensorConfig::groups);
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.core_init_filter = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.core_init_filter = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.core_init_filter = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionPoseSensorConfig::AbstractParamDescriptionConstPtr(new PositionPoseSensorConfig::ParamDescription<bool>("core_init_filter", "bool", 1, "call filter init using defined scale", "", &PositionPoseSensorConfig::core_init_filter)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionPoseSensorConfig::AbstractParamDescriptionConstPtr(new PositionPoseSensorConfig::ParamDescription<bool>("core_init_filter", "bool", 1, "call filter init using defined scale", "", &PositionPoseSensorConfig::core_init_filter)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.core_set_height = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.core_set_height = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.core_set_height = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionPoseSensorConfig::AbstractParamDescriptionConstPtr(new PositionPoseSensorConfig::ParamDescription<bool>("core_set_height", "bool", 4, "call filter init using defined height", "", &PositionPoseSensorConfig::core_set_height)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionPoseSensorConfig::AbstractParamDescriptionConstPtr(new PositionPoseSensorConfig::ParamDescription<bool>("core_set_height", "bool", 4, "call filter init using defined height", "", &PositionPoseSensorConfig::core_set_height)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.core_height = 0.1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.core_height = 20.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.core_height = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionPoseSensorConfig::AbstractParamDescriptionConstPtr(new PositionPoseSensorConfig::ParamDescription<double>("core_height", "double", 2, "height in m for init", "", &PositionPoseSensorConfig::core_height)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionPoseSensorConfig::AbstractParamDescriptionConstPtr(new PositionPoseSensorConfig::ParamDescription<double>("core_height", "double", 2, "height in m for init", "", &PositionPoseSensorConfig::core_height)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.pose_initial_scale = 0.001;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.pose_initial_scale = 30.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.pose_initial_scale = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionPoseSensorConfig::AbstractParamDescriptionConstPtr(new PositionPoseSensorConfig::ParamDescription<double>("pose_initial_scale", "double", 2, "value for initial scale", "", &PositionPoseSensorConfig::pose_initial_scale)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionPoseSensorConfig::AbstractParamDescriptionConstPtr(new PositionPoseSensorConfig::ParamDescription<double>("pose_initial_scale", "double", 2, "value for initial scale", "", &PositionPoseSensorConfig::pose_initial_scale)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.pose_fixed_scale = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.pose_fixed_scale = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.pose_fixed_scale = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionPoseSensorConfig::AbstractParamDescriptionConstPtr(new PositionPoseSensorConfig::ParamDescription<bool>("pose_fixed_scale", "bool", 2, "fix scale", "", &PositionPoseSensorConfig::pose_fixed_scale)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionPoseSensorConfig::AbstractParamDescriptionConstPtr(new PositionPoseSensorConfig::ParamDescription<bool>("pose_fixed_scale", "bool", 2, "fix scale", "", &PositionPoseSensorConfig::pose_fixed_scale)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.pose_fixed_p_ic = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.pose_fixed_p_ic = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.pose_fixed_p_ic = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionPoseSensorConfig::AbstractParamDescriptionConstPtr(new PositionPoseSensorConfig::ParamDescription<bool>("pose_fixed_p_ic", "bool", 2, "fix calibration state position", "", &PositionPoseSensorConfig::pose_fixed_p_ic)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionPoseSensorConfig::AbstractParamDescriptionConstPtr(new PositionPoseSensorConfig::ParamDescription<bool>("pose_fixed_p_ic", "bool", 2, "fix calibration state position", "", &PositionPoseSensorConfig::pose_fixed_p_ic)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.pose_fixed_q_ic = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.pose_fixed_q_ic = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.pose_fixed_q_ic = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionPoseSensorConfig::AbstractParamDescriptionConstPtr(new PositionPoseSensorConfig::ParamDescription<bool>("pose_fixed_q_ic", "bool", 2, "fix calibration state attitude", "", &PositionPoseSensorConfig::pose_fixed_q_ic)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionPoseSensorConfig::AbstractParamDescriptionConstPtr(new PositionPoseSensorConfig::ParamDescription<bool>("pose_fixed_q_ic", "bool", 2, "fix calibration state attitude", "", &PositionPoseSensorConfig::pose_fixed_q_ic)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.pose_fixed_p_wv = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.pose_fixed_p_wv = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.pose_fixed_p_wv = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionPoseSensorConfig::AbstractParamDescriptionConstPtr(new PositionPoseSensorConfig::ParamDescription<bool>("pose_fixed_p_wv", "bool", 2, "fix world vision position drift", "", &PositionPoseSensorConfig::pose_fixed_p_wv)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionPoseSensorConfig::AbstractParamDescriptionConstPtr(new PositionPoseSensorConfig::ParamDescription<bool>("pose_fixed_p_wv", "bool", 2, "fix world vision position drift", "", &PositionPoseSensorConfig::pose_fixed_p_wv)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.pose_fixed_q_wv = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.pose_fixed_q_wv = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.pose_fixed_q_wv = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionPoseSensorConfig::AbstractParamDescriptionConstPtr(new PositionPoseSensorConfig::ParamDescription<bool>("pose_fixed_q_wv", "bool", 2, "fix world vision attitude drift", "", &PositionPoseSensorConfig::pose_fixed_q_wv)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionPoseSensorConfig::AbstractParamDescriptionConstPtr(new PositionPoseSensorConfig::ParamDescription<bool>("pose_fixed_q_wv", "bool", 2, "fix world vision attitude drift", "", &PositionPoseSensorConfig::pose_fixed_q_wv)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.pose_noise_scale = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.pose_noise_scale = 10.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.pose_noise_scale = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionPoseSensorConfig::AbstractParamDescriptionConstPtr(new PositionPoseSensorConfig::ParamDescription<double>("pose_noise_scale", "double", 2, "propagation: noise scale (std. dev)", "", &PositionPoseSensorConfig::pose_noise_scale)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionPoseSensorConfig::AbstractParamDescriptionConstPtr(new PositionPoseSensorConfig::ParamDescription<double>("pose_noise_scale", "double", 2, "propagation: noise scale (std. dev)", "", &PositionPoseSensorConfig::pose_noise_scale)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.pose_noise_p_wv = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.pose_noise_p_wv = 10.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.pose_noise_p_wv = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionPoseSensorConfig::AbstractParamDescriptionConstPtr(new PositionPoseSensorConfig::ParamDescription<double>("pose_noise_p_wv", "double", 2, "propagation: noise p_wv (std. dev)", "", &PositionPoseSensorConfig::pose_noise_p_wv)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionPoseSensorConfig::AbstractParamDescriptionConstPtr(new PositionPoseSensorConfig::ParamDescription<double>("pose_noise_p_wv", "double", 2, "propagation: noise p_wv (std. dev)", "", &PositionPoseSensorConfig::pose_noise_p_wv)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.pose_noise_q_wv = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.pose_noise_q_wv = 10.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.pose_noise_q_wv = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionPoseSensorConfig::AbstractParamDescriptionConstPtr(new PositionPoseSensorConfig::ParamDescription<double>("pose_noise_q_wv", "double", 2, "propagation: noise q_wv (std. dev)", "", &PositionPoseSensorConfig::pose_noise_q_wv)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionPoseSensorConfig::AbstractParamDescriptionConstPtr(new PositionPoseSensorConfig::ParamDescription<double>("pose_noise_q_wv", "double", 2, "propagation: noise q_wv (std. dev)", "", &PositionPoseSensorConfig::pose_noise_q_wv)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.pose_noise_p_ic = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.pose_noise_p_ic = 10.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.pose_noise_p_ic = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionPoseSensorConfig::AbstractParamDescriptionConstPtr(new PositionPoseSensorConfig::ParamDescription<double>("pose_noise_p_ic", "double", 2, "propagation: noise p_ic (std. dev)", "", &PositionPoseSensorConfig::pose_noise_p_ic)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionPoseSensorConfig::AbstractParamDescriptionConstPtr(new PositionPoseSensorConfig::ParamDescription<double>("pose_noise_p_ic", "double", 2, "propagation: noise p_ic (std. dev)", "", &PositionPoseSensorConfig::pose_noise_p_ic)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.pose_noise_q_ic = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.pose_noise_q_ic = 10.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.pose_noise_q_ic = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionPoseSensorConfig::AbstractParamDescriptionConstPtr(new PositionPoseSensorConfig::ParamDescription<double>("pose_noise_q_ic", "double", 2, "propagation: noise q_ic (std. dev)", "", &PositionPoseSensorConfig::pose_noise_q_ic)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionPoseSensorConfig::AbstractParamDescriptionConstPtr(new PositionPoseSensorConfig::ParamDescription<double>("pose_noise_q_ic", "double", 2, "propagation: noise q_ic (std. dev)", "", &PositionPoseSensorConfig::pose_noise_q_ic)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.pose_noise_meas_p = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.pose_noise_meas_p = 10.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.pose_noise_meas_p = 0.01;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionPoseSensorConfig::AbstractParamDescriptionConstPtr(new PositionPoseSensorConfig::ParamDescription<double>("pose_noise_meas_p", "double", 2, "noise for measurement sensor (std. dev)", "", &PositionPoseSensorConfig::pose_noise_meas_p)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionPoseSensorConfig::AbstractParamDescriptionConstPtr(new PositionPoseSensorConfig::ParamDescription<double>("pose_noise_meas_p", "double", 2, "noise for measurement sensor (std. dev)", "", &PositionPoseSensorConfig::pose_noise_meas_p)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.pose_noise_meas_q = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.pose_noise_meas_q = 10.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.pose_noise_meas_q = 0.01;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionPoseSensorConfig::AbstractParamDescriptionConstPtr(new PositionPoseSensorConfig::ParamDescription<double>("pose_noise_meas_q", "double", 2, "noise for measurement sensor (std. dev)", "", &PositionPoseSensorConfig::pose_noise_meas_q)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionPoseSensorConfig::AbstractParamDescriptionConstPtr(new PositionPoseSensorConfig::ParamDescription<double>("pose_noise_meas_q", "double", 2, "noise for measurement sensor (std. dev)", "", &PositionPoseSensorConfig::pose_noise_meas_q)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.pose_delay = -2.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.pose_delay = 2.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.pose_delay = 0.02;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionPoseSensorConfig::AbstractParamDescriptionConstPtr(new PositionPoseSensorConfig::ParamDescription<double>("pose_delay", "double", 2, "fix delay in seconds", "", &PositionPoseSensorConfig::pose_delay)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionPoseSensorConfig::AbstractParamDescriptionConstPtr(new PositionPoseSensorConfig::ParamDescription<double>("pose_delay", "double", 2, "fix delay in seconds", "", &PositionPoseSensorConfig::pose_delay)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.position_noise_meas = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.position_noise_meas = 10.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.position_noise_meas = 0.01;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionPoseSensorConfig::AbstractParamDescriptionConstPtr(new PositionPoseSensorConfig::ParamDescription<double>("position_noise_meas", "double", 2, "noise for measurement sensor (std. dev)", "", &PositionPoseSensorConfig::position_noise_meas)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionPoseSensorConfig::AbstractParamDescriptionConstPtr(new PositionPoseSensorConfig::ParamDescription<double>("position_noise_meas", "double", 2, "noise for measurement sensor (std. dev)", "", &PositionPoseSensorConfig::position_noise_meas)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.position_yaw_init = -180.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.position_yaw_init = 180.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.position_yaw_init = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionPoseSensorConfig::AbstractParamDescriptionConstPtr(new PositionPoseSensorConfig::ParamDescription<double>("position_yaw_init", "double", 2, "initial value of yaw", "", &PositionPoseSensorConfig::position_yaw_init)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionPoseSensorConfig::AbstractParamDescriptionConstPtr(new PositionPoseSensorConfig::ParamDescription<double>("position_yaw_init", "double", 2, "initial value of yaw", "", &PositionPoseSensorConfig::position_yaw_init)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.position_delay = -2.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.position_delay = 2.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.position_delay = 0.02;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionPoseSensorConfig::AbstractParamDescriptionConstPtr(new PositionPoseSensorConfig::ParamDescription<double>("position_delay", "double", 2, "fix delay in seconds", "", &PositionPoseSensorConfig::position_delay)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionPoseSensorConfig::AbstractParamDescriptionConstPtr(new PositionPoseSensorConfig::ParamDescription<double>("position_delay", "double", 2, "fix delay in seconds", "", &PositionPoseSensorConfig::position_delay)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.position_noise_p_ip = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.position_noise_p_ip = 10.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.position_noise_p_ip = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionPoseSensorConfig::AbstractParamDescriptionConstPtr(new PositionPoseSensorConfig::ParamDescription<double>("position_noise_p_ip", "double", 2, "propagation: noise p_ip (std. dev)", "", &PositionPoseSensorConfig::position_noise_p_ip)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionPoseSensorConfig::AbstractParamDescriptionConstPtr(new PositionPoseSensorConfig::ParamDescription<double>("position_noise_p_ip", "double", 2, "propagation: noise p_ip (std. dev)", "", &PositionPoseSensorConfig::position_noise_p_ip)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.position_fixed_p_ip = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.position_fixed_p_ip = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.position_fixed_p_ip = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionPoseSensorConfig::AbstractParamDescriptionConstPtr(new PositionPoseSensorConfig::ParamDescription<bool>("position_fixed_p_ip", "bool", 2, "fix calibration state position", "", &PositionPoseSensorConfig::position_fixed_p_ip)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionPoseSensorConfig::AbstractParamDescriptionConstPtr(new PositionPoseSensorConfig::ParamDescription<bool>("position_fixed_p_ip", "bool", 2, "fix calibration state position", "", &PositionPoseSensorConfig::position_fixed_p_ip)));
//#line 245 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 245 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(PositionPoseSensorConfig::AbstractGroupDescriptionConstPtr(new PositionPoseSensorConfig::GroupDescription<PositionPoseSensorConfig::DEFAULT, PositionPoseSensorConfig>(Default)));
//#line 366 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<PositionPoseSensorConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<PositionPoseSensorConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<PositionPoseSensorConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    PositionPoseSensorConfig __max__;
    PositionPoseSensorConfig __min__;
    PositionPoseSensorConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const PositionPoseSensorConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static PositionPoseSensorConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &PositionPoseSensorConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const PositionPoseSensorConfig &PositionPoseSensorConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const PositionPoseSensorConfig &PositionPoseSensorConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const PositionPoseSensorConfig &PositionPoseSensorConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<PositionPoseSensorConfig::AbstractParamDescriptionConstPtr> &PositionPoseSensorConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<PositionPoseSensorConfig::AbstractGroupDescriptionConstPtr> &PositionPoseSensorConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const PositionPoseSensorConfigStatics *PositionPoseSensorConfig::__get_statics__()
  {
    const static PositionPoseSensorConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = PositionPoseSensorConfigStatics::get_instance();

    return statics;
  }

//#line 31 "/home/radu/tiltUp3_ws/src/ethzasl_msf/msf_updates/cfg/PositionPoseSensor.cfg"
      const int PositionPoseSensor_INIT_FILTER = 1;
//#line 32 "/home/radu/tiltUp3_ws/src/ethzasl_msf/msf_updates/cfg/PositionPoseSensor.cfg"
      const int PositionPoseSensor_MISC = 2;
//#line 33 "/home/radu/tiltUp3_ws/src/ethzasl_msf/msf_updates/cfg/PositionPoseSensor.cfg"
      const int PositionPoseSensor_SET_HEIGHT = 4;
}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __POSITIONPOSESENSORRECONFIGURATOR_H__
