//#line 2 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the mav_ilqr_control package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __mav_ilqr_control__ILQRCONTROLLERCONFIG_H__
#define __mav_ilqr_control__ILQRCONTROLLERCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace mav_ilqr_control
{
  class iLQRControllerConfigStatics;

  class iLQRControllerConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }

      virtual void clamp(iLQRControllerConfig &config, const iLQRControllerConfig &max, const iLQRControllerConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const iLQRControllerConfig &config1, const iLQRControllerConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, iLQRControllerConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const iLQRControllerConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, iLQRControllerConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const iLQRControllerConfig &config) const = 0;
      virtual void getValue(const iLQRControllerConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T iLQRControllerConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T (iLQRControllerConfig::* field);

      virtual void clamp(iLQRControllerConfig &config, const iLQRControllerConfig &max, const iLQRControllerConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const iLQRControllerConfig &config1, const iLQRControllerConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, iLQRControllerConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const iLQRControllerConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, iLQRControllerConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const iLQRControllerConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const iLQRControllerConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, iLQRControllerConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, iLQRControllerConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<iLQRControllerConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(iLQRControllerConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("phi_gain"==(*_i)->name){phi_gain = boost::any_cast<double>(val);}
        if("theta_gain"==(*_i)->name){theta_gain = boost::any_cast<double>(val);}
        if("psi_gain"==(*_i)->name){psi_gain = boost::any_cast<double>(val);}
        if("x_gain"==(*_i)->name){x_gain = boost::any_cast<double>(val);}
        if("vx_gain"==(*_i)->name){vx_gain = boost::any_cast<double>(val);}
        if("y_gain"==(*_i)->name){y_gain = boost::any_cast<double>(val);}
        if("vy_gain"==(*_i)->name){vy_gain = boost::any_cast<double>(val);}
        if("z_gain"==(*_i)->name){z_gain = boost::any_cast<double>(val);}
        if("dz_gain"==(*_i)->name){dz_gain = boost::any_cast<double>(val);}
        if("thrust_gain"==(*_i)->name){thrust_gain = boost::any_cast<double>(val);}
        if("roll_ref_gain"==(*_i)->name){roll_ref_gain = boost::any_cast<double>(val);}
        if("pitch_ref_gain"==(*_i)->name){pitch_ref_gain = boost::any_cast<double>(val);}
        if("yaw_rate_command_gain"==(*_i)->name){yaw_rate_command_gain = boost::any_cast<double>(val);}
        if("alpha_gain"==(*_i)->name){alpha_gain = boost::any_cast<double>(val);}
        if("K_yaw"==(*_i)->name){K_yaw = boost::any_cast<double>(val);}
        if("yaw_rate_limit"==(*_i)->name){yaw_rate_limit = boost::any_cast<double>(val);}
        if("speed_limit_on"==(*_i)->name){speed_limit_on = boost::any_cast<bool>(val);}
        if("vx_limit"==(*_i)->name){vx_limit = boost::any_cast<double>(val);}
        if("vy_limit"==(*_i)->name){vy_limit = boost::any_cast<double>(val);}
        if("vz_limit"==(*_i)->name){vz_limit = boost::any_cast<double>(val);}
        if("position_limit_on"==(*_i)->name){position_limit_on = boost::any_cast<bool>(val);}
        if("x_limit_inf"==(*_i)->name){x_limit_inf = boost::any_cast<double>(val);}
        if("x_limit_sup"==(*_i)->name){x_limit_sup = boost::any_cast<double>(val);}
        if("y_limit_inf"==(*_i)->name){y_limit_inf = boost::any_cast<double>(val);}
        if("y_limit_sup"==(*_i)->name){y_limit_sup = boost::any_cast<double>(val);}
        if("z_limit_inf"==(*_i)->name){z_limit_inf = boost::any_cast<double>(val);}
        if("z_limit_sup"==(*_i)->name){z_limit_sup = boost::any_cast<double>(val);}
      }
    }

    double phi_gain;
double theta_gain;
double psi_gain;
double x_gain;
double vx_gain;
double y_gain;
double vy_gain;
double z_gain;
double dz_gain;
double thrust_gain;
double roll_ref_gain;
double pitch_ref_gain;
double yaw_rate_command_gain;
double alpha_gain;
double K_yaw;
double yaw_rate_limit;
bool speed_limit_on;
double vx_limit;
double vy_limit;
double vz_limit;
bool position_limit_on;
double x_limit_inf;
double x_limit_sup;
double y_limit_inf;
double y_limit_sup;
double z_limit_inf;
double z_limit_sup;

    bool state;
    std::string name;

    
}groups;



//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double phi_gain;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double theta_gain;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double psi_gain;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double x_gain;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double vx_gain;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double y_gain;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double vy_gain;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double z_gain;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double dz_gain;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double thrust_gain;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double roll_ref_gain;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double pitch_ref_gain;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double yaw_rate_command_gain;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double alpha_gain;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double K_yaw;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double yaw_rate_limit;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool speed_limit_on;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double vx_limit;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double vy_limit;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double vz_limit;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool position_limit_on;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double x_limit_inf;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double x_limit_sup;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double y_limit_inf;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double y_limit_sup;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double z_limit_inf;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double z_limit_sup;
//#line 228 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("iLQRControllerConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const iLQRControllerConfig &__max__ = __getMax__();
      const iLQRControllerConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const iLQRControllerConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const iLQRControllerConfig &__getDefault__();
    static const iLQRControllerConfig &__getMax__();
    static const iLQRControllerConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const iLQRControllerConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void iLQRControllerConfig::ParamDescription<std::string>::clamp(iLQRControllerConfig &config, const iLQRControllerConfig &max, const iLQRControllerConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class iLQRControllerConfigStatics
  {
    friend class iLQRControllerConfig;

    iLQRControllerConfigStatics()
    {
iLQRControllerConfig::GroupDescription<iLQRControllerConfig::DEFAULT, iLQRControllerConfig> Default("Default", "", 0, 0, true, &iLQRControllerConfig::groups);
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.phi_gain = 0.1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.phi_gain = 10000.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.phi_gain = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(iLQRControllerConfig::AbstractParamDescriptionConstPtr(new iLQRControllerConfig::ParamDescription<double>("phi_gain", "double", 0, "proportional gain of roll angle", "", &iLQRControllerConfig::phi_gain)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(iLQRControllerConfig::AbstractParamDescriptionConstPtr(new iLQRControllerConfig::ParamDescription<double>("phi_gain", "double", 0, "proportional gain of roll angle", "", &iLQRControllerConfig::phi_gain)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.theta_gain = 0.1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.theta_gain = 10000.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.theta_gain = 20.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(iLQRControllerConfig::AbstractParamDescriptionConstPtr(new iLQRControllerConfig::ParamDescription<double>("theta_gain", "double", 0, "proportional gain of pitch angle", "", &iLQRControllerConfig::theta_gain)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(iLQRControllerConfig::AbstractParamDescriptionConstPtr(new iLQRControllerConfig::ParamDescription<double>("theta_gain", "double", 0, "proportional gain of pitch angle", "", &iLQRControllerConfig::theta_gain)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.psi_gain = 0.1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.psi_gain = 10000.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.psi_gain = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(iLQRControllerConfig::AbstractParamDescriptionConstPtr(new iLQRControllerConfig::ParamDescription<double>("psi_gain", "double", 0, "proportional gain of yaw angle", "", &iLQRControllerConfig::psi_gain)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(iLQRControllerConfig::AbstractParamDescriptionConstPtr(new iLQRControllerConfig::ParamDescription<double>("psi_gain", "double", 0, "proportional gain of yaw angle", "", &iLQRControllerConfig::psi_gain)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.x_gain = 0.1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.x_gain = 10000.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.x_gain = 3.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(iLQRControllerConfig::AbstractParamDescriptionConstPtr(new iLQRControllerConfig::ParamDescription<double>("x_gain", "double", 0, "proportional gain of x axis", "", &iLQRControllerConfig::x_gain)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(iLQRControllerConfig::AbstractParamDescriptionConstPtr(new iLQRControllerConfig::ParamDescription<double>("x_gain", "double", 0, "proportional gain of x axis", "", &iLQRControllerConfig::x_gain)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.vx_gain = 0.1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.vx_gain = 10000.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.vx_gain = 0.1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(iLQRControllerConfig::AbstractParamDescriptionConstPtr(new iLQRControllerConfig::ParamDescription<double>("vx_gain", "double", 0, "derivative gain of x axis", "", &iLQRControllerConfig::vx_gain)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(iLQRControllerConfig::AbstractParamDescriptionConstPtr(new iLQRControllerConfig::ParamDescription<double>("vx_gain", "double", 0, "derivative gain of x axis", "", &iLQRControllerConfig::vx_gain)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.y_gain = 0.1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.y_gain = 10000.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.y_gain = 3.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(iLQRControllerConfig::AbstractParamDescriptionConstPtr(new iLQRControllerConfig::ParamDescription<double>("y_gain", "double", 0, "proportional gain of y axis", "", &iLQRControllerConfig::y_gain)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(iLQRControllerConfig::AbstractParamDescriptionConstPtr(new iLQRControllerConfig::ParamDescription<double>("y_gain", "double", 0, "proportional gain of y axis", "", &iLQRControllerConfig::y_gain)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.vy_gain = 0.1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.vy_gain = 10000.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.vy_gain = 0.1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(iLQRControllerConfig::AbstractParamDescriptionConstPtr(new iLQRControllerConfig::ParamDescription<double>("vy_gain", "double", 0, "derivative gain of y axis", "", &iLQRControllerConfig::vy_gain)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(iLQRControllerConfig::AbstractParamDescriptionConstPtr(new iLQRControllerConfig::ParamDescription<double>("vy_gain", "double", 0, "derivative gain of y axis", "", &iLQRControllerConfig::vy_gain)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.z_gain = 0.1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.z_gain = 10000.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.z_gain = 15.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(iLQRControllerConfig::AbstractParamDescriptionConstPtr(new iLQRControllerConfig::ParamDescription<double>("z_gain", "double", 0, "proportional gain of z axis", "", &iLQRControllerConfig::z_gain)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(iLQRControllerConfig::AbstractParamDescriptionConstPtr(new iLQRControllerConfig::ParamDescription<double>("z_gain", "double", 0, "proportional gain of z axis", "", &iLQRControllerConfig::z_gain)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.dz_gain = 0.1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.dz_gain = 10000.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.dz_gain = 0.3;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(iLQRControllerConfig::AbstractParamDescriptionConstPtr(new iLQRControllerConfig::ParamDescription<double>("dz_gain", "double", 0, "derivative gain of z axis", "", &iLQRControllerConfig::dz_gain)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(iLQRControllerConfig::AbstractParamDescriptionConstPtr(new iLQRControllerConfig::ParamDescription<double>("dz_gain", "double", 0, "derivative gain of z axis", "", &iLQRControllerConfig::dz_gain)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.thrust_gain = 0.1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.thrust_gain = 1000.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.thrust_gain = 0.1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(iLQRControllerConfig::AbstractParamDescriptionConstPtr(new iLQRControllerConfig::ParamDescription<double>("thrust_gain", "double", 0, "thrust control weight", "", &iLQRControllerConfig::thrust_gain)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(iLQRControllerConfig::AbstractParamDescriptionConstPtr(new iLQRControllerConfig::ParamDescription<double>("thrust_gain", "double", 0, "thrust control weight", "", &iLQRControllerConfig::thrust_gain)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.roll_ref_gain = 0.1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.roll_ref_gain = 1000.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.roll_ref_gain = 5.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(iLQRControllerConfig::AbstractParamDescriptionConstPtr(new iLQRControllerConfig::ParamDescription<double>("roll_ref_gain", "double", 0, "roll control weight", "", &iLQRControllerConfig::roll_ref_gain)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(iLQRControllerConfig::AbstractParamDescriptionConstPtr(new iLQRControllerConfig::ParamDescription<double>("roll_ref_gain", "double", 0, "roll control weight", "", &iLQRControllerConfig::roll_ref_gain)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.pitch_ref_gain = 0.1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.pitch_ref_gain = 1000.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.pitch_ref_gain = 10.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(iLQRControllerConfig::AbstractParamDescriptionConstPtr(new iLQRControllerConfig::ParamDescription<double>("pitch_ref_gain", "double", 0, "pitch control weight", "", &iLQRControllerConfig::pitch_ref_gain)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(iLQRControllerConfig::AbstractParamDescriptionConstPtr(new iLQRControllerConfig::ParamDescription<double>("pitch_ref_gain", "double", 0, "pitch control weight", "", &iLQRControllerConfig::pitch_ref_gain)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.yaw_rate_command_gain = 0.1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.yaw_rate_command_gain = 1000.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.yaw_rate_command_gain = 10.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(iLQRControllerConfig::AbstractParamDescriptionConstPtr(new iLQRControllerConfig::ParamDescription<double>("yaw_rate_command_gain", "double", 0, "yaw_rate control weight", "", &iLQRControllerConfig::yaw_rate_command_gain)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(iLQRControllerConfig::AbstractParamDescriptionConstPtr(new iLQRControllerConfig::ParamDescription<double>("yaw_rate_command_gain", "double", 0, "yaw_rate control weight", "", &iLQRControllerConfig::yaw_rate_command_gain)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.alpha_gain = 0.1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.alpha_gain = 1000.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.alpha_gain = 5.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(iLQRControllerConfig::AbstractParamDescriptionConstPtr(new iLQRControllerConfig::ParamDescription<double>("alpha_gain", "double", 0, "tilt control weight", "", &iLQRControllerConfig::alpha_gain)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(iLQRControllerConfig::AbstractParamDescriptionConstPtr(new iLQRControllerConfig::ParamDescription<double>("alpha_gain", "double", 0, "tilt control weight", "", &iLQRControllerConfig::alpha_gain)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.K_yaw = 0.01;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.K_yaw = 1000.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.K_yaw = 10.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(iLQRControllerConfig::AbstractParamDescriptionConstPtr(new iLQRControllerConfig::ParamDescription<double>("K_yaw", "double", 0, "yaw gain", "", &iLQRControllerConfig::K_yaw)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(iLQRControllerConfig::AbstractParamDescriptionConstPtr(new iLQRControllerConfig::ParamDescription<double>("K_yaw", "double", 0, "yaw gain", "", &iLQRControllerConfig::K_yaw)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.yaw_rate_limit = 0.01;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.yaw_rate_limit = 10.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.yaw_rate_limit = 10.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(iLQRControllerConfig::AbstractParamDescriptionConstPtr(new iLQRControllerConfig::ParamDescription<double>("yaw_rate_limit", "double", 0, "yaw rate command limit", "", &iLQRControllerConfig::yaw_rate_limit)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(iLQRControllerConfig::AbstractParamDescriptionConstPtr(new iLQRControllerConfig::ParamDescription<double>("yaw_rate_limit", "double", 0, "yaw rate command limit", "", &iLQRControllerConfig::yaw_rate_limit)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.speed_limit_on = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.speed_limit_on = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.speed_limit_on = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(iLQRControllerConfig::AbstractParamDescriptionConstPtr(new iLQRControllerConfig::ParamDescription<bool>("speed_limit_on", "bool", 0, "active speed safety limit", "", &iLQRControllerConfig::speed_limit_on)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(iLQRControllerConfig::AbstractParamDescriptionConstPtr(new iLQRControllerConfig::ParamDescription<bool>("speed_limit_on", "bool", 0, "active speed safety limit", "", &iLQRControllerConfig::speed_limit_on)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.vx_limit = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.vx_limit = 1000.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.vx_limit = 5.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(iLQRControllerConfig::AbstractParamDescriptionConstPtr(new iLQRControllerConfig::ParamDescription<double>("vx_limit", "double", 0, "vx limit", "", &iLQRControllerConfig::vx_limit)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(iLQRControllerConfig::AbstractParamDescriptionConstPtr(new iLQRControllerConfig::ParamDescription<double>("vx_limit", "double", 0, "vx limit", "", &iLQRControllerConfig::vx_limit)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.vy_limit = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.vy_limit = 1000.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.vy_limit = 5.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(iLQRControllerConfig::AbstractParamDescriptionConstPtr(new iLQRControllerConfig::ParamDescription<double>("vy_limit", "double", 0, "vy limit", "", &iLQRControllerConfig::vy_limit)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(iLQRControllerConfig::AbstractParamDescriptionConstPtr(new iLQRControllerConfig::ParamDescription<double>("vy_limit", "double", 0, "vy limit", "", &iLQRControllerConfig::vy_limit)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.vz_limit = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.vz_limit = 1000.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.vz_limit = 5.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(iLQRControllerConfig::AbstractParamDescriptionConstPtr(new iLQRControllerConfig::ParamDescription<double>("vz_limit", "double", 0, "vz limit", "", &iLQRControllerConfig::vz_limit)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(iLQRControllerConfig::AbstractParamDescriptionConstPtr(new iLQRControllerConfig::ParamDescription<double>("vz_limit", "double", 0, "vz limit", "", &iLQRControllerConfig::vz_limit)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.position_limit_on = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.position_limit_on = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.position_limit_on = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(iLQRControllerConfig::AbstractParamDescriptionConstPtr(new iLQRControllerConfig::ParamDescription<bool>("position_limit_on", "bool", 0, "active position safety limit", "", &iLQRControllerConfig::position_limit_on)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(iLQRControllerConfig::AbstractParamDescriptionConstPtr(new iLQRControllerConfig::ParamDescription<bool>("position_limit_on", "bool", 0, "active position safety limit", "", &iLQRControllerConfig::position_limit_on)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.x_limit_inf = -10.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.x_limit_inf = 5.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.x_limit_inf = -1.58;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(iLQRControllerConfig::AbstractParamDescriptionConstPtr(new iLQRControllerConfig::ParamDescription<double>("x_limit_inf", "double", 0, "x position lower limit", "", &iLQRControllerConfig::x_limit_inf)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(iLQRControllerConfig::AbstractParamDescriptionConstPtr(new iLQRControllerConfig::ParamDescription<double>("x_limit_inf", "double", 0, "x position lower limit", "", &iLQRControllerConfig::x_limit_inf)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.x_limit_sup = -5.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.x_limit_sup = 10.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.x_limit_sup = 1.48;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(iLQRControllerConfig::AbstractParamDescriptionConstPtr(new iLQRControllerConfig::ParamDescription<double>("x_limit_sup", "double", 0, "x position upper limit", "", &iLQRControllerConfig::x_limit_sup)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(iLQRControllerConfig::AbstractParamDescriptionConstPtr(new iLQRControllerConfig::ParamDescription<double>("x_limit_sup", "double", 0, "x position upper limit", "", &iLQRControllerConfig::x_limit_sup)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.y_limit_inf = -10.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.y_limit_inf = 5.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.y_limit_inf = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(iLQRControllerConfig::AbstractParamDescriptionConstPtr(new iLQRControllerConfig::ParamDescription<double>("y_limit_inf", "double", 0, "y position lower limit", "", &iLQRControllerConfig::y_limit_inf)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(iLQRControllerConfig::AbstractParamDescriptionConstPtr(new iLQRControllerConfig::ParamDescription<double>("y_limit_inf", "double", 0, "y position lower limit", "", &iLQRControllerConfig::y_limit_inf)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.y_limit_sup = -5.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.y_limit_sup = 10.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.y_limit_sup = 1.7;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(iLQRControllerConfig::AbstractParamDescriptionConstPtr(new iLQRControllerConfig::ParamDescription<double>("y_limit_sup", "double", 0, "y position upper limit", "", &iLQRControllerConfig::y_limit_sup)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(iLQRControllerConfig::AbstractParamDescriptionConstPtr(new iLQRControllerConfig::ParamDescription<double>("y_limit_sup", "double", 0, "y position upper limit", "", &iLQRControllerConfig::y_limit_sup)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.z_limit_inf = -10.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.z_limit_inf = 5.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.z_limit_inf = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(iLQRControllerConfig::AbstractParamDescriptionConstPtr(new iLQRControllerConfig::ParamDescription<double>("z_limit_inf", "double", 0, "z position lower limit", "", &iLQRControllerConfig::z_limit_inf)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(iLQRControllerConfig::AbstractParamDescriptionConstPtr(new iLQRControllerConfig::ParamDescription<double>("z_limit_inf", "double", 0, "z position lower limit", "", &iLQRControllerConfig::z_limit_inf)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.z_limit_sup = -5.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.z_limit_sup = 10.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.z_limit_sup = 1.77;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(iLQRControllerConfig::AbstractParamDescriptionConstPtr(new iLQRControllerConfig::ParamDescription<double>("z_limit_sup", "double", 0, "z position upper limit", "", &iLQRControllerConfig::z_limit_sup)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(iLQRControllerConfig::AbstractParamDescriptionConstPtr(new iLQRControllerConfig::ParamDescription<double>("z_limit_sup", "double", 0, "z position upper limit", "", &iLQRControllerConfig::z_limit_sup)));
//#line 245 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 245 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(iLQRControllerConfig::AbstractGroupDescriptionConstPtr(new iLQRControllerConfig::GroupDescription<iLQRControllerConfig::DEFAULT, iLQRControllerConfig>(Default)));
//#line 366 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<iLQRControllerConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<iLQRControllerConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<iLQRControllerConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    iLQRControllerConfig __max__;
    iLQRControllerConfig __min__;
    iLQRControllerConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const iLQRControllerConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static iLQRControllerConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &iLQRControllerConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const iLQRControllerConfig &iLQRControllerConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const iLQRControllerConfig &iLQRControllerConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const iLQRControllerConfig &iLQRControllerConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<iLQRControllerConfig::AbstractParamDescriptionConstPtr> &iLQRControllerConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<iLQRControllerConfig::AbstractGroupDescriptionConstPtr> &iLQRControllerConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const iLQRControllerConfigStatics *iLQRControllerConfig::__get_statics__()
  {
    const static iLQRControllerConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = iLQRControllerConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __ILQRCONTROLLERRECONFIGURATOR_H__
